### ISSUE TITLE
[Question] Is it possible to count the numbers of ->, !! and ? operators using Kastree?

### ISSUE THREAD

**Issue by albertininm** [cretz/kastree#28]

**Comment by cretz** [comment]
Sure, just parse the code and then use the visitor to check operators.

**Comment by albertininm** [comment]
Thanks for your response @cretz 
Could you please show me an example of counting these operators in a snippet?
I just tried to run the code described in README with a very small change and it broke.
```kotlin
import kastree.ast.MutableVisitor
import kastree.ast.Node
import kastree.ast.Visitor
import kastree.ast.Writer
import kastree.ast.psi.Converter
import kastree.ast.psi.Parser

fun main(args: Array<String>) {
    val code = """
    package foo
    fun bar() {
        // Print hello
        println("Hello, World!")
    }
    val x: IntArray = intArrayOf(1, 2, 3)
    println(x[0])
    fun baz() = println("Hello, again!")
""".trimIndent()
    val file = Parser.parseFile(code)
    val extrasMap = Converter.WithExtras()
    println(Writer.write(file, extrasMap))

    var strings = emptyList<String>()
    Visitor.visit(file) { v, _ ->
        println (v is Node.Expr.ArrayAccess)
        if (v is Node.Expr.StringTmpl.Elem.Regular) strings += v.str
    }
    println(strings)

    val newFile = MutableVisitor.preVisit(file) { v, _ ->
        if (v !is Node.Expr.StringTmpl.Elem.Regular) v
        else v.copy(str = v.str.replace("Hello", "Howdy"))
    }

    println(Writer.write(newFile, extrasMap))

// Prints [Hello, World!, Hello, again!]
}
```
I got this error:
```
Exception in thread "main" ParseError(file=KtFile: temp.kt, errors=[PsiErrorElement:Expecting a top level declaration, PsiErrorElement:Expecting a top level declaration, PsiErrorElement:Expecting a top level declaration, PsiErrorElement:Expecting a top level declaration, PsiErrorElement:Expecting a top level declaration, PsiErrorElement:Expecting a top level declaration, PsiErrorElement:Expecting a top level declaration])
	at kastree.ast.psi.Parser.parseFile(Parser.kt:25)
	at kastree.ast.psi.Parser.parseFile$default(Parser.kt:23)
	at MainKt.main(main.kt:22)

Process finished with exit code 1
```

As you can see, I only added 
```kotlin
    val x: IntArray = intArrayOf(1, 2, 3)
    println(x[0])
```
to your code example.

**Comment by cretz** [comment]
Gonna be some time, sorry, I don't work with Kotlin in my day job anymore.

**Comment by albertininm** [comment]
Ok, thanks.
