### ISSUE TITLE
Update Kotlin compiler dependency and use embeddable version

### ISSUE THREAD

**Issue by TAGC** [cretz/kastree#4]
I added `com.github.cretz.kastree:kastree-ast-psi:0.1.0"` to my gradle build config and tried parsing the example code snippet from the README:

```kotlin
val code = """
    package foo

    fun bar() {
        // Print hello
        println("Hello, World!")
    }

    fun baz() = println("Hello, again!")
""".trimIndent()
val file = Parser.parseFile(code)
```

I get this stacktrace:

```
e: java.lang.IllegalStateException: failed to analyze: java.lang.reflect.InvocationTargetException
        at org.jetbrains.kotlin.analyzer.AnalysisResult.throwIfError(AnalysisResult.kt:56)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:125)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:161)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:57)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:96)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1$2.invoke(CompileServiceImpl.kt:441)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1$2.invoke(CompileServiceImpl.kt:101)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:1020)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:101)
        at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:1062)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:1019)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:440)
        at jdk.internal.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:567)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:800)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:682)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:681)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.GeneratedMethodAccessor204.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:51)
        at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:27)
        at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.runAnnotationProcessing(Kapt3Extension.kt:213)
        at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:178)
        at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:96)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:95)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:105)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:82)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:375)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:67)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:107)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:366)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:120)
        ... 29 more
Caused by: com.sun.tools.javac.processing.AnnotationProcessingError: java.lang.NoSuchMethodError: org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(Lcom/intellij/openapi/Disposable;Lorg/jetbrains/kotlin/config/CompilerConfiguration;Lorg/jetbrains/kotlin/cli/jvm/compiler/EnvironmentConfigFiles;)Lorg/jetbrains/kotlin/cli/jvm/compiler/KotlinCoreEnvironment;
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:980)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:884)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2200(JavacProcessingEnvironment.java:108)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1206)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1315)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1246)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1143)
        ... 45 more
Caused by: java.lang.NoSuchMethodError: org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(Lcom/intellij/openapi/Disposable;Lorg/jetbrains/kotlin/config/CompilerConfiguration;Lorg/jetbrains/kotlin/cli/jvm/compiler/EnvironmentConfigFiles;)Lorg/jetbrains/kotlin/cli/jvm/compiler/KotlinCoreEnvironment;
        at kastree.ast.psi.Parser$proj$2.invoke(Parser.kt:16)
        at kastree.ast.psi.Parser$proj$2.invoke(Parser.kt:14)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at kastree.ast.psi.Parser.getProj(Parser.kt)
        at kastree.ast.psi.Parser.parsePsiFile(Parser.kt:30)
        at kastree.ast.psi.Parser.parseFile(Parser.kt:23)
        at kastree.ast.psi.Parser.parseFile$default(Parser.kt:23)
        at com.mycompany.testmaster.nodegen.processing.ElementaryNodeAnnotationProcessor.inspectElement(ElementaryNodeAnnotationProcessor.kt:47)
        at com.mycompany.testmaster.nodegen.processing.NodeAnnotationProcessor.process(NodeAnnotationProcessor.kt:39)
        at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:99)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:968)
        ... 51 more
```

I'm using Kotlin 1.2.71 with the Java 9 JDK on 64-bit Windows 10.

**Comment by cretz** [comment]
This is surely due to upgrading the library and it no longer having the expected method. I will change this issue to be about upgrading the Kotlin version. Can you provide your full build.gradle?

**Comment by TAGC** [comment]
Not sure why, but it works now. One change is that is Kotlin 1.3 (stable) got released and I've updated my projects to that.

**Comment by TAGC** [comment]
Interesting. All the tests in one of my projects fail if I merely add kastree as a dependency:

```diff
@@ -20,10 +20,19 @@ dependencies {
     testImplementation("com.google.testing.compile:compile-testing:0.15")
     testImplementation("org.slf4j:slf4j-api:1.7.25")
     testImplementation("org.slf4j:slf4j-simple:1.7.25")
+    testImplementation("com.github.cretz.kastree:kastree-ast-psi:0.1.0")
 }
```

![mintty_2018-10-31_11-07-11](https://user-images.githubusercontent.com/1588951/47784339-29beb200-dcfd-11e8-9c3c-c5b2e9e39390.png)

Trying to isolate the cause of this.

**Comment by TAGC** [comment]
Minimal reproduction.

Create a Gradle project with `build.gradle.kts` defined as:

```kotlin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm") version "1.3.0"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(kotlin("stdlib-jdk8"))
    implementation("com.google.testing.compile:compile-testing:0.15")

    // Problematic import when combined with compile-testing
    implementation("com.github.cretz.kastree:kastree-ast-psi:0.1.0")
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}
```

Then a file under the project directory, `src/main/kotlin/experiment.kt` containing:

```kotlin
import com.google.testing.compile.Compiler.javac

fun main(args: Array<String>) {
    javac().withProcessors()
}
```

Commenting out the kastree import allows this to run successfully. Otherwise, this exception gets thrown:

```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.copyOf([Ljava/lang/Object;)Lcom/google/common/collect/ImmutableList;
	at com.google.testing.compile.Compiler.withProcessors(Compiler.java:71)
	at experiment.ExperimentKt.main(experiment.kt:6)
```

**Comment by cretz** [comment]
I will take a look at some point (may not be right away). Probably a Guava conflict somewhere. I wonder if, instead of including the kastree lib, you changed it to `implementation('org.jetbrains.kotlin:kotlin-compiler:1.2.51')` which is what the psi stuff transitively uses.

**Comment by TAGC** [comment]
Yeah, the same exception gets thrown for that as well. Most likely an issue with the compile-testing library then, right? I'm about to submit this as an issue on [their project repo](https://github.com/google/compile-testing).

**Comment by cretz** [comment]
Unsure which side it is a problem with downstream, would have to test further and check the transitive dependency tree to see which Guava is included or if one is shaded or something. But we have at least confirmed it is not specific to this library.

**Comment by TAGC** [comment]
In the new issue I opened, @tbroyer said:

> org.jetbrains.kotlin:kotlin-compiler:1.2.51 bundles its dependencies (including Guava) into the JAR, shadowing the "real" Guava; and it probably uses a version of Guava that didn't have that method. It will thus break anything that also depends on Guava (or any other bundled dependency: JNA, JavaSlang, GNU Trove, JANSI, JDOM, etc.)
>
> Either kotlin-compiler is not meant to be used as a dependency, or they have a packaging issue.

Looking into this, I found [this seemingly-related issue](https://youtrack.jetbrains.com/issue/KT-8638) on the Kotlin issue tracker.

So I'm wondering, what happens if you try to replace `kotlin-compiler` with `kotlin-compiler-embeddable` here:

https://github.com/cretz/kastree/blob/e10463e430cf8a94c36ca35104b2ac89a4fa8d45/build.gradle#L69-L76

**Comment by cretz** [comment]
Figured something like that was happening. Quite disappointing that Kotlin would shade Guava without changing the package name. I will look in to using the embeddable form. Thanks.
