### ISSUE TITLE
Found interface org.jetbrains.kotlin.psi.KtDoubleColonExpression, but class was expected

### ISSUE THREAD

**Issue by fab1an** [cretz/kastree#45]
Hi, kastree fails to parse the following:

```kotlin

package test

import kastree.ast.psi.Parser
import kotlin.test.Test

class KastreeTest {

    @Test
    fun testBug() {
        val data = """
            fun test() {
                println(Int::class)
            }
        """.trimIndent()

        val fileNode = Parser.parseFile(data)
    }
}

```

Exception:
```
java.lang.IncompatibleClassChangeError: Found interface org.jetbrains.kotlin.psi.KtDoubleColonExpression, but class was expected
	at kastree.ast.psi.Converter$Companion.getQuestionMarks$kastree_ast_psi(Converter.kt:823)
	at kastree.ast.psi.Converter.convertDoubleColonRefClass(Converter.kt:209)
	at kastree.ast.psi.Converter.convertExpr(Converter.kt:260)
	at kastree.ast.psi.Converter.convertBinaryOp(Converter.kt:93)
	at kastree.ast.psi.Converter.convertExpr(Converter.kt:255)
	at kastree.ast.psi.Converter.convertProperty(Converter.kt:433)
	at kastree.ast.psi.Converter.convertDecl(Converter.kt:197)
	at kastree.ast.psi.Converter.convertStmtNo(Converter.kt:483)
	at kastree.ast.psi.Converter.convertBlock(Converter.kt:101)
	at kastree.ast.psi.Converter.convertFuncBody(Converter.kt:318)
	at kastree.ast.psi.Converter.convertFunc(Converter.kt:314)
	at kastree.ast.psi.Converter.convertDecl(Converter.kt:195)
	at kastree.ast.psi.Converter.convertFile(Converter.kt:293)
	at kastree.ast.psi.Parser.parseFile(Parser.kt:23)
	at kastree.ast.psi.Parser.parseFile$default(Parser.kt:23)
```

**Comment by cretz** [comment]
Per the README, I am afraid this library is no longer developed. See https://github.com/kotlinx/ast for an alternative.

**Comment by fab1an** [comment]
Thank you for your answer. I have switched to to kastree from kotlinx/ast, because the latter is really troublesome to get, since it's not on maven central, and you have to guess a version at bintray that works: https://github.com/kotlinx/ast/issues/63
