### ISSUE TITLE
Unable to parse code using DOS line endings

### ISSUE THREAD

**Issue by TAGC** [cretz/kastree#7]
Trying to parse a string representation of code with `Parser.parseFile` will fail if the string uses DOS line endings (`\r\n`). This doesn't seem like a bug with kastree itself but the Kotlin compiler. It might be worthwhile to just make kastree convert line endings before it tries parsing anything. For reference here's an example of a stacktrace resulting from this issue:

```
WARN: org.jetbrains.kotlin.lexer._JetLexer
org.jetbrains.kotlin.lexer.KotlinLexerException: Error: could not match input
 at ''
package example

fun foo() {

}
        at org.jetbrains.kotlin.lexer._JetLexer.zzScanError(_JetLexer.java:806)
        at org.jetbrains.kotlin.lexer._JetLexer.advance(_JetLexer.java:1506)
        at org.jetbrains.kotlin.com.intellij.lexer.FlexAdapter.locateToken(FlexAdapter.java:110)
        at org.jetbrains.kotlin.com.intellij.lexer.FlexAdapter.getTokenType(FlexAdapter.java:69)
        at org.jetbrains.kotlin.com.intellij.lang.impl.TokenSequence$Builder.performLexing(TokenSequence.java:71)
        at org.jetbrains.kotlin.com.intellij.lang.impl.PsiBuilderImpl.performLexing(PsiBuilderImpl.java:188)
        at org.jetbrains.kotlin.com.intellij.lang.impl.PsiBuilderImpl.<init>(PsiBuilderImpl.java:161)
        at org.jetbrains.kotlin.com.intellij.lang.impl.PsiBuilderImpl.<init>(PsiBuilderImpl.java:115)
        at org.jetbrains.kotlin.com.intellij.lang.impl.PsiBuilderFactoryImpl.createBuilder(PsiBuilderFactoryImpl.java:37)
        at org.jetbrains.kotlin.psi.stubs.elements.KtFileElementType.doParseContents(KtFileElementType.java:80)
        at org.jetbrains.kotlin.com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:49)
        at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:192)
        at org.jetbrains.kotlin.com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:553)
        at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:191)
        at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:245)
        at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:39)
        at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:190)
        at org.jetbrains.kotlin.com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:728)
        at org.jetbrains.kotlin.com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
        at kastree.ast.psi.Parser$$special$$inlined$collectDescendantsOfType$3.visitElement(psiUtils.kt:227)
        at org.jetbrains.kotlin.com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:34)
        at org.jetbrains.kotlin.com.intellij.psi.PsiRecursiveElementVisitor.visitFile(PsiRecursiveElementVisitor.java:59)
        at org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:210)
        at kastree.ast.psi.Parser.parseFile(Parser.kt:54)
        at kastree.ast.psi.Parser.parseFile$default(Parser.kt:23)
        at com.mycompany.experiment.MainKt.main(main.kt:16)
        at com.mycompany.experiment.MainKt.main(main.kt)
Exception in thread "main" ParseError(file=KtFile: temp.kt, errors=[PsiErrorElement:Expecting a top level declaration])
        at kastree.ast.psi.Parser.parseFile(Parser.kt:25)
        at kastree.ast.psi.Parser.parseFile$default(Parser.kt:23)
        at com.mycompany.experiment.MainKt.main(main.kt:16)
        at com.mycompany.experiment.MainKt.main(main.kt)
```

**Comment by cretz** [comment]
> This doesn't seem like a bug with kastree itself but the Kotlin compiler.

I don't think there's anything we can do. If it doesn't match the Kotlin grammar, I am not sure we should do anything in advance to try to make it match, whether it's line endings, or case sensitivity, or whatever. I would rather not preprocess strings of code for any reason and instead give back exactly what the Kotlin compiler gives back.

**Comment by TAGC** [comment]
That's fine.
